version: "3"

services:
  server:
    container_name: node_mongo
    build: .
    command: npm start
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/meu-pijama/server
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    # restart: always
    # command: mongod --auth
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
